### ISSUE TITLE
跳过视频会不会被封号啊

### ISSUE THREAD

**Issue by s1771915465** [lifegpc/fuckchaoxing#4]
跳过视频会不会被封号啊

**Comment by lifegpc** [comment]
我以前试过一直15倍速，没有什么问题

**Comment by s1771915465** [comment]
我的意思是，那个一键跳过视频的按钮，会不会封号




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:05
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
我以前试过一直15倍速，没有什么问题

**Comment by lifegpc** [comment]
本质上差不多的，那个跳过就相当于是更快的倍速（跳过其实就是进度直接跳到最后面

**Comment by s1771915465** [comment]
主要是我看百度上说超星倍速太高，或者拖进度条会被，有点慌，我已经全部刷完了。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:07
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
本质上差不多的，那个跳过就相当于是更快的倍速（跳过其实就是进度直接跳到最后面

**Comment by lifegpc** [comment]
啊，我去年上半年就是这样刷的，什么事都没有。至于调倍速，数据上一定有异常的，它原本的播放器是每次播放、暂停或者每隔一分钟上传一次进度。

**Comment by s1771915465** [comment]
所以这取决于超星搞不搞事喽？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:12
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
啊，我去年上半年就是这样刷的，什么事都没有。至于调倍速，数据上一定有异常的，它原本的播放器是每次播放、暂停或者每隔一分钟上传一次进度。

**Comment by lifegpc** [comment]
就是这样。如果慌的话，那就乖乖地1倍速吧。

**Comment by s1771915465** [comment]
别，我已经全章节跳过视频完了，慌也没用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:16
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
就是这样。如果慌的话，那就乖乖地1倍速吧。

**Comment by lifegpc** [comment]
那我也没办法了:(

**Comment by s1771915465** [comment]
不过1倍速不至于，超星本身就支持2倍速，有2倍速选项的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:16
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
就是这样。如果慌的话，那就乖乖地1倍速吧。

**Comment by lifegpc** [comment]
部分视频倍速播放是被禁用的。

**Comment by s1771915465** [comment]
我那个可以开二倍速，不过反正我是全部用了你那个一键跳过的按钮。。凉没凉，看命



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:25
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
部分视频倍速播放是被禁用的。

**Comment by s1771915465** [comment]
要不是一百多个视频，我都懒得安装插件。。。看结果咯，不过封号不是马上的事情吗。。都这么久过去了
他不至于秋后算账吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lifegpc"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 晚上11:17
收件人: "lifegpc/fuckchaoxing"<fuckchaoxing@noreply.github.com&gt;; 
抄送: "冷封"<1771915465@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lifegpc/fuckchaoxing] 跳过视频会不会被封号啊 (#4)





 
那我也没办法了:(
